# Site settings
title: Home Country . US
tagline: A Land of Enchantment
description: > # this means to ignore newlines until "baseurl:"
  Experimental. Ephemeral. Ephemera.
baseurl: "" # the subpath of your site, e.g. /blog
url: "https://airbeagle.github.io/AirBeagle/" # the base hostname & protocol for your site

# Plugins
gems: ["jekyll-paginate"]

# Build settings
markdown: kramdown
sass:
  sass_dir: assets/sass

# Pagination
paginate: 4
paginate_path: "/blog/page:num/"
